name = "hellxstudio"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

build = { command = "pnpm build" }
compatibility_date = "2024-12-18"

[env.production]
name = "hellxstudio-prod"
routes = [
  { pattern = "hellxstudio.kindle.com", zone_name = "kindle.com" }
]
